### ISSUE TITLE
slack_bot_id lookup script seems to be failing

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-online-store#95] opened 2017-07-17 12:16 UTC
I think this is related to #94 -- Slack seems to have changed the way that bots are created/managed

```
APP/PROC/WEB/0Looking up BOT_ID for 'watsonshoppingbot'Jul 17, 2017 12:58:21.826 PM
APP/PROC/WEB/0Error: Missing BOT_ID or invalid SLACK_BOT_USER.Jul 17, 2017 12:58:22.013 PM
APP/PROC/WEB/0could not find user because api_call did not return 'ok'Jul 17, 2017 12:58:22.013 PM
APP/PROC/WEB/0DEBUG:urllib3.connectionpool:https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 55Jul 17, 2017 12:58:22.014 PM
```

**Comment by scottdangelo** [comment] 2017-07-18 14:31
I am not able to reproduce this problem. Slack does not appear to have changed. When running via manual setup, the BOT_ID is successfully obtained and the app works as expected.
I'll be pushing up a patch with improved documentation in the README. I'm wondering if this is a configuration error?

**Comment by scottdangelo** [comment] 2017-08-14 18:34
Closing this as "Cannot Reproduce".

**Closed as completed by scottdangelo** 2017-08-14 18:34 UTC

**Comment by DarrenZastruga** [comment] 2017-11-26 23:31
@scottdangelo 

Not sure why @stevemart never replied, but I have been experiencing the same error message when trying to use the watsononlinestore run.py script. When the script runs the line "slack_client.api_call("users.list")", the api_call returns "{u'ok': False, u'error': u'invalid_auth'}". 

This is strange, because I have gone back and confirmed that my SLACK_BOT_TOKEN is correct - it actually works fine when running the script locally, and also when using Slack's API tester for the users.list method. It only fails when deploying the app from IBM Cloud. 

Any thoughts?

**Comment by DarrenZastruga** [comment] 2017-11-27 02:57
@scottdangelo 

Update: I was only able to get this Slack API call to work by using the full URL with the Requests library: 
api_call = requests.get('https://slack.com/api/users.list?token=<mySlack_bot_token>&pretty=1').json()

For whatever reason, I kept getting the invalid_auth error when attempting to use slack_client.api_call("users.list"). I wonder if it has something to do with the way the token is pulled - I couldn't get the URL to work using the variable "slack_bot_token" in the URL and had to just insert my full token into the URL string. 

Hope this info helps figure out the issue.
